name: kos_pondokhasanah2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3 # Menambahkan provider untuk state management (opsional)
  intl: ^0.18.0 # Menambahkan intl untuk format tanggal
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
